name = "m3u8proxy"
main = "src/index.ts"
compatibility_date = "2024-03-03"  # Update to the latest compatibility date
type = "javascript"

workers_dev = true  # Keep this true for development

# Enable Smart Caching for M3U8 Streaming
[vars]
CACHE_TTL = 3600  # Cache M3U8 files for 1 hour

# Optimize Worker Placement
[placement]
mode = "smart"  # Deploy in the closest Cloudflare regions
