name = "m3u8proxy"
main = "src/index.ts"
compatibility_date = "2025-03-15"
type = "javascript"

workers_dev = true

[vars]
CACHE_TTL = 3600
CACHE_CONTROL = "public, max-age=3600, stale-while-revalidate=60"

[placement]
mode = "smart"

[build]
command = "npm install && npm run build"

[compatibility_flags]
- stream_body_concurrency
- headers_case_sensitivity
