name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main  # Adjust if using a different branch
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Use latest version

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'  # Cache dependencies for faster builds

      - name: Install Dependencies
        run: npm ci  # Ensures clean installs & caching

  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Reduce timeout to 30 mins
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Publish to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: publish
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}  # Better security
